apiVersion: apps/v1
kind: Deployment
metadata:
  name: recomm_song
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song_recommendation
  template:
    metadata:
      labels:
        app: song_recommendation
    spec:
      containers:
      - name: cv-app
        image: gcr.io/recomm-deploy/recommapp:v1
        ports:
        - containerPort: 8501